site_name: kuid
nav:
  - Home: index.md
  - Getting Started: 01-getting-started/01_install.md
  - Resources:
    - About: 02-resources/01_about.md
    - Inventory:
      - About: 02-resources/02-inventory/01_about.md
      - Region: 02-resources/02-inventory/02_region.md
      - Site: 02-resources/02-inventory/03_site.md
      - Rack: 02-resources/02-inventory/04_rack.md
      - NodeGroup: 02-resources/02-inventory/05_nodegroup.md
      - Node: 02-resources/02-inventory/06_node.md
      - ModuleBay: 02-resources/02-inventory/07_modulebay.md
      - Module: 02-resources/02-inventory/08_module.md
      - Nodeitem: 02-resources/02-inventory/09_nodeitem.md
      - Endpoint: 02-resources/02-inventory/10_endpoint.md
      - Link: 02-resources/02-inventory/11_link.md
      - Cluster: 02-resources/02-inventory/12_cluster.md
      - NodeSet: 02-resources/02-inventory/13_nodeset.md
      - LinkSet: 02-resources/02-inventory/14_linkset.md
    - Identifiers:
      - About: 02-resources/03-identifiers/01_about.md
      - IPAM:
        - About: 02-resources/03-identifiers/ipam/01_ipam_about.md
      - ASN: 
        - About: 02-resources/03-identifiers/asn/01_asn_about.md
        - ASIndex: 02-resources/03-identifiers/asn/02_asn_index.md
        - AS Range: 02-resources/03-identifiers/asn/03_asn_range.md
        - AS: 02-resources/03-identifiers/asn/04_asn.md
        - AS Entry: 02-resources/03-identifiers/asn/05_asn_entry.md
      - VLAN: 
        - About: 02-resources/03-identifiers/vlan/01_vlan_about.md
        - VLANIndex: 02-resources/03-identifiers/vlan/02_vlan_index.md
        - VLAN Range: 02-resources/03-identifiers/vlan/03_vlan_range.md
        - VLAN: 02-resources/03-identifiers/vlan/04_vlan.md
        - VLAN Entry: 02-resources/03-identifiers/vlan/05_vlan_entry.md
      - VXLAN: 
        - About: 02-resources/03-identifiers/vxlan/01_vxlan_about.md
        - VXLANIndex: 02-resources/03-identifiers/vxlan/02_vxlan_index.md
        - VXLAN Range: 02-resources/03-identifiers/vxlan/03_vxlan_range.md
        - VXLAN: 02-resources/03-identifiers/vxlan/04_vxlan.md
        - VXLAN Entry: 02-resources/03-identifiers/vxlan/05_vxlan_entry.md
  - Release Notes:
    - "0.0.1": 06-rn/0.0.1.md
  - Community: 
    - Community: 07-community/01_about.md
    - FAQ: 07-community/02_faq.md

site_author: Wim Henderickx
site_description: >-
  Kuid is a system in which resource identifiers and inventory information is stored
# repository
repo_name: kuidio/docs
repo_url: https://github.com/kuidio/docs
site_url: "https://docs.kuidio.dev"
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    #- header.autohide
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.integrate
    - toc.follow
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/sitemap
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/flask.svg

# Plugins
plugins:
  - search
  - mermaid2
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sdcio
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/fHCNahWR2T
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kform
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
      #dedent_subsections: true
      base_path:
        - ./
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde