name: "Pull Request Docs Build Check"
on:
    pull_request:

env:
  MKDOCS_MATERIAL_VER: 9.1.4

jobs:
  build-docs:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - shell: bash
        run: |
          cat versions.env >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          repository: 'kuidio/kuid'
          # TODO: add the ref back again was just temp fix
          ref: '${{ env.KUID_SERVER_VERSION }}'
          path: 'kuid-repo'
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'kuid-repo/go.mod'
          cache-dependency-path: |
            kuid-repo/go.sum
      - shell: bash
        run: |
          cat versions.env >> $GITHUB_ENV
          cat configmap-input-vars.yaml.tmpl | envsubst > kuid-repo/artifacts/in/configmap-input-vars.yaml
          cd kuid-repo
          make artifacts
          cd ..
          # remove the HEADER from artifacts
          find ./ -name *yaml -exec grep -l "####### HEADER END #######" {} ';' | xargs -I{} gawk -i inplace '/####### HEADER END #######/ {p=1;next}p' {}
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-mkdocs-image \
            -f Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Build MkDocs Site
        run: |
          docker run -v $(pwd):/docs my-mkdocs-image build --strict -c -f mkdocs.yml -d build
      - name: Store html build result
        uses: actions/upload-artifact@v4
        with:
            name: kuidio.github.io-${{ github.sha }}.zip
            path: |
              build
      - name: Set summary
        run: |
            echo "### Documentation built and can be downloaded from the job summary page. :rocket:"  >> $GITHUB_STEP_SUMMARY
