name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "docs-*"
    tags:
      - "v*"

env:
  MKDOCS_MATERIAL_VER: 9.1.4

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Deploy MkDocs Site
        run: |
          docker run -v $(pwd):/docs my-mkdocs-image gh-deploy --force --strict
